# Default values for devnet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: anmol1696
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

exposer:
  image: anmol1696/exposer:latest
  port: 8081

# API for interacting with the charts for devnet
# TODO: need a way to create state reaching jobs, those will run user bash scripts
# after the chain has been initialized, get the chain to a state and then complete
chains:
  osmosis:
    name: osmosis
    image: anmol1696/osmosis:latest
    home: /root/.osmosisd
    binary: osmosisd
    prefix: osmo
    denom: uosmo
    coins: 100000000000000uosmo,100000000000000uion
    numValidators: 4
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    wasm:
      enabled: true
      permissionless: true
    localPorts:
      rpc: 26659
      rest: 1319
  juno:
    name: juno
    image: anmol1696/juno:latest
    home: /root/.juno
    binary: junod
    prefix: juno
    denom: ujuno
    coins: 100000000000000ujuno
    numValidators: 2
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    wasm:
      enabled: true
      permissionless: true
    localPorts:
      rpc: 26654
      rest: 1314
  wasmd:
    name: wasmd
    image: anmol1696/wasmd:latest
    home: /root/.wasmd
    binary: wasmd
    prefix: wasm
    denom: stake
    coins: 100000000000000ucosm,100000000000000stake
    numValidators: 4
    hdPath: m/44'/118'/0'/0/0
    coinType: 118
    wasm:
      enabled: true
      permissionless: true
    localPorts:
      rpc: 26653
      rest: 1313
  #persistence:
  #  name: persistence
  #  image: anmol1696/persistence:latest
  #  binary: persistenceCore
  #  prefix: persistence
  #  denom: uxprt
  #  coins: 100000000000000uxprt
  #  numValidators: 5 # number of unique validator nodes
  #  wasm:
  #    enabled: true
  #    permissionless: false
  #cosmos:
  #  name: cosmos
  #  image: anmol1696/gaia:latest
  #  binary: gaiad
  #  prefix: cosmos
  #  denom: stake
  #  coins: 100000000000000uxprt
  #  numValidators: 3
  #  wasm:
  #    enabled: false

# TODO: ability to check the srcConnection and destConnection to use
relayers:
  rly1:
    name: osmo-wasm
    kind: ts-relayer
    image: anmol1696/ts-relayer:latest
    replicas: 1 # these are unique replicas, currently only support a single replica
    chains:
      - osmosis
      - wasmd
  rly2:
    name: osmo-juno
    kind: ts-relayer
    image: anmol1696/ts-relayer:latest
    replicas: 1
    chains:
      - osmosis
      - juno

explorer:
  enabled: true # Flag to enable disable explorer
  type: ping-pub
  #image: persistenceone/ping-pub-explorer
  image: anmol1696/explorer
  localhost: true
  localPorts:
    rest: 8080

faucet:
  enabled: false # will create faucet for all chains
