# Example values.yaml file will create 2 chains with 4 validators,
# a ts-relayer between them and the explorer
chains:
  - name: osmosis-1
    type: osmosis
    numValidators: 4
    ports:
      rest: 1313
      rpc: 26653
  - name: wasmd
    type: wasmd
    numValidators: 4
    ports:
      rpc: 26659
      rest: 1319
  - name: juno-0
    type: juno
    numValidators: 4
    ports:
      rest: 1315
      rpc: 26655
  - name: cosmoshub-1
    type: cosmos
    numValidators: 4
    ports:
      rest: 1317
      rpc: 26657

relayers:
  - name: osmo-wasm
    type: ts-relayer
    replicas: 1
    chains:
      - osmosis-1
      - wasmd
  - name: osmos-juno
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - juno-0
  - name: osmos-cosmos
    type: hermes
    replicas: 1
    chains:
      - osmosis-1
      - cosmoshub-1

explorer:
  enabled: true

